### PR TITLE
add the authentication for the RESTful API

### PR DESCRIPTION
**Pull request by hcchien**
Using the token base authentication for the RESTful API.

### CODE REVIEW

**Comment by nickhsine** [comment]
Do we need to have any code changes on FE servers?

**Comment by hcchien** [comment]
we will need to pass the token in HTTP header.

**Comment by nickhsine** [comment]
How can I get token? 
The code change seems that we have to pass the accounts info?

**Comment by hcchien** [comment]
The request will look like
"curl -H "Authorization: Basic YWRtaW46c2VjcmV0" -i http://localhost:8080/drafts"

**Pull request merged**
